### ISSUE TITLE
Add a option to behave like component in another tool bar

### ISSUE THREAD

**Issue by X1353135** [peter-frentrup/NppMenuSearch#10]
Thank you for you provide the nice plugin.
NppMenuSearch plugin always behaves as a individual  tool bar now.
Thus, unnecessary blank space appears when I use NppMenuSearch plugin with CustomizeToolBar plugin with enabling "wrap toolbar" option.
It would be nice if NppMenuSearch plugin supports a option to behave like a component in another tool bar.
![menuseach1](https://user-images.githubusercontent.com/29348192/27982630-471eb28a-63d9-11e7-8349-bd1a4e1e4f67.PNG)

**Comment by peter-frentrup** [comment]
I do not think this is possible in a stable way, since a Win32 toolbar cannot contain anything except toolbar buttons (IIRC):

I would have to insert invisible "fake" buttons to save space, somehow monitor their location when the window resizes, and then put the searchbox as a floaing window above that position.

If anything goes wrong, it would be a mess.

**Comment by X1353135** [comment]
Thank you for your comment.

**Comment by peter-frentrup** [comment]
Closed, because I see no viable way to implement this.
